"""Add image_url to FoodItem

Revision ID: 6f86f05ad888
Revises: a21b477b63c0
Create Date: 2026-01-02 18:32:01.279420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f86f05ad888'
down_revision = 'a21b477b63c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
