"""Add DeliveryOrder table

Revision ID: a21b477b63c0
Revises: 4c1db7e8d064
Create Date: 2026-01-02 18:01:04.454686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21b477b63c0'
down_revision = '4c1db7e8d064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_order_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_order_timestamp'))

    op.drop_table('delivery_order')
    # ### end Alembic commands ###
